// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

function createSupabaseClient() {
  const isServer = typeof window === "undefined";
  const serverEnv = isServer && typeof process !== "undefined" ? process.env : {};

  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to server process.env during SSR (server-side rendering)
  const SUPABASE_URL =
    import.meta.env["VITE_SUPABASE_URL"] ||
    serverEnv["SUPABASE_URL"] ||
    serverEnv["VITE_SUPABASE_URL"];

  const SUPABASE_KEY =
    import.meta.env["VITE_SUPABASE_ANON_KEY"] ||
    import.meta.env["VITE_SUPABASE_PUBLISHABLE_KEY"] ||
    serverEnv["SUPABASE_ANON_KEY"] ||
    serverEnv["SUPABASE_PUBLISHABLE_KEY"] ||
    serverEnv["VITE_SUPABASE_ANON_KEY"] ||
    serverEnv["VITE_SUPABASE_PUBLISHABLE_KEY"];

  if (!SUPABASE_URL || !SUPABASE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["SUPABASE_URL / VITE_SUPABASE_URL"] : []),
      ...(!SUPABASE_KEY ? ["SUPABASE_ANON_KEY / VITE_SUPABASE_ANON_KEY"] : []),
    ];
    const message = `Missing required Supabase environment variable(s): ${missing.join(", ")}. Please configure them in your Vercel environment settings.`;
    if (!isServer || (typeof process !== "undefined" && process.env["NODE_ENV"] === "production")) {
      console.error(`[Supabase FATAL] ${message}`);
      throw new Error(message);
    }
    console.warn(`[Supabase] ${message}`);
  }

  return createClient<Database>(
    SUPABASE_URL || "https://placeholder.supabase.co",
    SUPABASE_KEY || "placeholder-key",
    {
      global: {
        fetch: createSupabaseFetch(SUPABASE_KEY || "placeholder-key"),
      },
      auth: {
        storage: typeof window !== "undefined" ? localStorage : undefined,
        persistSession: true,
        autoRefreshToken: true,
      },
    },
  );
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
